version: '3.5'

services:


    node-front:
      image: node-front
      build: ../1.5/
      ports:
        - "5000:5000"
      container_name: node-front

    node-back:
      image: node-back
      build: ../1.6/
      volumes:
        - ../1.6/logs.txt:/logs.txt
      ports:
        - "8000:8000"
      container_name: node-back
      links:
        - redis
        - db
      depends_on:
        - redis
        - db
      environment:
        - REDIS=redis
        - DB_USERNAME=user
        - DB_PASSWORD=pw
        - DB_HOST=db

    redis:
      image: redis
      container_name: redis
      ports:
        - "6379:6379"


    db:
      image: postgres
      container_name: db
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=pw
