version: '3.5'

services:

    node-front:
      image: node-front
      build: ../1.5/
      ports:
        - "5000:5000"
      container_name: node-front

    node-back:
      image: node-back
      build: ../1.6/
      volumes:
        - ../1.6/logs.txt:/logs.txt
      ports:
        - "8000:8000"
      container_name: node-back
      links:
        - redis
      depends_on:
        - redis
      environment:
        - REDIS=redis
    redis:
      image: redis
      container_name: redis
      ports:
        - "6379:6379"
